language: java

jdk:
  - oraclejdk8

install: mvn verify clean --fail-never --quiet -DskipTests=true -Dinvoker.skip=true
script: mvn verify

sudo: false
cache:
  directories:
    - $HOME/.m2
    - target/it-repo
